version: '3'

services:
  web:
    image: news-stories-expr-server:latest
    build:
      context: .
    ports:
      - "11111:5000"
    volumes:
      - /data/anwala/IMLS/StoryGraph/graphs:/usr/src/app/static/graphs 
      - /data/anwala/IMLS/StoryGraph/graph-cursors:/usr/src/app/graphs
      - /data/anwala/IMLS/StoryGraph/generic:/usr/src/app/generic